Examples/Counter/CounterApp.swift, Examples/RandomNumberGenerator/RandomNumberGeneratorApp.swift, Examples/WindowProperties/WindowPropertiesApp.swift, Package.swift, README.md, Sources/SwiftCrossUI/App.swift, Sources/SwiftCrossUI/WindowProperties.swift, Sources/SwiftCrossUI/_App.swift
Allows defining window properties from your app.
Currently it has the following properties:
- `title`
- `defaultWidth`
- `defaultHeight`
- `resizable` 
`title` is required, while the other values are optional and default to the previously hard-coded values if not set.
=> Add WindowProperties to App protocol

Sources/Gtk/Widgets/Box.swift, Sources/Gtk/Widgets/Grid.swift, Sources/Gtk/Widgets/Orientable.swift, Sources/Gtk/Widgets/SingleChildBox.swift, Sources/SwiftCrossUI/Gtk/Gtk.swift, Sources/SwiftCrossUI/Views/EitherView.swift, Sources/SwiftCrossUI/Views/ForEach.swift, Sources/SwiftCrossUI/Views/ForegroundColorView.swift, Sources/SwiftCrossUI/Views/OptionalView.swift, Sources/SwiftCrossUI/Views/PaddingView.swift
Reworked Box usage across modifiers so ForEach can retrieve the correct orientation for its context.
Previously the following would create vertical items in swift-cross-ui while in SwiftUI it generates the views inside ForEach horizontally. 
```swift
HStack {
ForEach(...) {
...
}
}
```
This PR aligns our ForEach with Apples SwiftUI behaviour. From here on out if you want to wrap content (eg ModifierView) without caring about orientation, use `GtkSingleChildBox`.
=> ForEach rework

Package.swift
See https://github.com/apple/swift-package-manager/pull/5527 for the context. The fix was landed in Swift 5.8.
=> Add warning for PKG_CONFIG_PATH on Windows

Sources/QtBackend/QtBackend.swift
- Add Qt back-end implementation of slider
The `QSlider` widget doesn't seem to have an equivalent of 'decimal places'
=> Add slider for QtBackend

Package.resolved, README.md, Sources/SwiftCrossUI/SwiftCrossUI.docc/Basic Usage.md, Sources/SwiftCrossUI/SwiftCrossUI.docc/Examples.md, Sources/SwiftCrossUI/SwiftCrossUI.docc/SwiftCrossUI.md
Added the following examples to `Examples.md` and wrote a short description for each:
- SpitExample
- StressTestExample
- SpreadsheetExample
- ControlsExample
Categorized documentation pages. Currently using the categories `App Structure` (Apple's name for that category), `Views`, `States`, and `Implementation Details`. Descriptions for most of those categories are missing at the moment.
Some small changes to the overview of SwiftCrossUI and the README were also made, namely changing the formatting of the package import because its changed slightly since they were written, and touching up some wording here and there.
=> Add new examples to documentation and categorize pages

Examples/Sources/SelectedBackend/SelectedBackend.swift, Package.swift, Sources/WinUIBackend/WinUIBackend.swift
Example apps that didn't specify the `Backend` typealias were failing under `WinUIBackend` because it didn't have a default value.
See https://github.com/stackotter/swift-cross-ui/commit/26627bdd148ea53e4dab70af823fff577836c409 which removed need for explicit backend typealias in all backends except for `WinUIBackend`
=> Fix build errors when running examples using WinUIBackend

Sources/SwiftCrossUI/Color.swift
In particular, the instance method `opacity` and the static constant `clear`.
=> Add more features from `SwiftUI.Color`

Package.resolved, Package.swift, Sources/AppKitBackend/AppKitBackend.swift
* Created a default first menu item implementation, which is better than a dummy because this presents a standard "**About MyApp**" and ability to quit the app, similar to the default first menu item that `SwiftUI` creates by default on **macOS**.
It looks like the following:
=> Add a default first menu item implementation.

Package.swift, README.md, Sources/AppKitBackend/AppKitBackend.swift, Sources/DefaultBackend/DefaultBackend.swift, Sources/GtkBackend/GtkBackend.swift, Sources/SwiftCrossUI/Backend/AppBackend.swift, Sources/SwiftCrossUI/Scenes/WindowGroupNode.swift, Sources/SwiftCrossUI/Views/Toggle.swift, Sources/UIKitBackend/BaseWidget.swift, Sources/UIKitBackend/Font+UIFont.swift, Sources/UIKitBackend/UIColor+Color.swift, Sources/UIKitBackend/UIKitBackend+Alert.swift, Sources/UIKitBackend/UIKitBackend+Container.swift, Sources/UIKitBackend/UIKitBackend+Control.swift, Sources/UIKitBackend/UIKitBackend+Passive.swift, Sources/UIKitBackend/UIKitBackend+Progress.swift, Sources/UIKitBackend/UIKitBackend+Window.swift, Sources/UIKitBackend/UIKitBackend.swift, Sources/WinUIBackend/WinUIBackend.swift
Incomplete features:
- Menus (as discussed in Discord, `UIMenu` is incompatible with the current API)
- `Picker` (only supported on iOS) and `Slider` (only supported on iOS & Mac Catalyst)
- SplitView (how to handle this on mobile is an open question)
- Table (need column widths in order to render well)
- Open/Save file dialogs (probably not even possible on all UIKit platforms)
=> UIKit backend

Sources/SwiftCrossUI/Views/Picker.swift, Sources/UIKitBackend/UIKitBackend+Control.swift, Sources/UIKitBackend/UIKitBackend+Picker.swift
This implements two variants of `Picker`, one based on `UIPickerView` and one based on `UITableView`. This is the logic I use for deciding which version to display:
https://github.com/stackotter/swift-cross-ui/blob/98717e895aa791b7bf88808534ed2167cb582f9b/Sources/UIKitBackend/UIKitBackend%2BPicker.swift#L135-L145
Basically, I use `UIPickerView` wherever it works, and `UITableView` everywhere else.
=> Implement Picker for tvOS & Mac Catalyst

Sources/UIKitBackend/UIKitBackend.swift, Sources/UIKitBackend/UIViewRepresentable.swift
=> [UIKitBackend] Custom Application Delegates & `UIViewRepresentable`

Examples/Package.resolved, Package.resolved, Package.swift, Sources/AppKitBackend/NSViewRepresentable.swift, Sources/UIKitBackend/UIKitBackend+Passive.swift, Sources/UIKitBackend/UIKitBackend.swift
Just a slightly edited version of #105.
=> Implement `NSViewRepresentable` (cleaned up version of #105)

.github/workflows/swift-macos.yml, Sources/AppKitBackend/AppKitBackend.swift, Tests/SwiftCrossUITests/SwiftCrossUITests.swift
After debugging the CI, I discovered that the CI renders at 1x scale instead of 2x scale (retina). This causes the text to get kerned differently and ends up changing the layout in ways that can't be adjusted for by just dividing by two.
This PR is based off ideas from https://github.com/pointfreeco/swift-snapshot-testing/pull/533
The fix was to override the `backingScaleFactor` of `NSWindow` to `1.0` from a subclass. I also overrode the color space while I was at it just in case.
=> Fix basic AppKitBackend layout test in CI

Sources/UIKitBackend/KeyboardToolbar.swift, Sources/UIKitBackend/UIKitBackend+Control.swift
prevents buttons from flashing on view updates
=> Cache toolbar items for update

Sources/AppKitBackend/AppKitBackend.swift, Sources/Gtk/Generated/GestureLongPress.swift, Sources/Gtk3Backend/Gtk3Backend.swift, Sources/GtkBackend/GtkBackend.swift, Sources/GtkCodeGen/GtkCodeGen.swift, Sources/SwiftCrossUI/Backend/AppBackend.swift, Sources/SwiftCrossUI/Modifiers/OnTapGestureModifier.swift, Sources/UIKitBackend/UIKitBackend+Control.swift, Sources/WinUIBackend/WinUIBackend.swift
Implements right-click and long-press. Currently not implemented in Gtk3 or WinUI. I'm also not sold on the argument label because `onTapGesture(gesture:) {}` looks a little odd.
=> More tap gestures

Sources/AppKitBackend/AppKitBackend.swift, Sources/Gtk3Backend/Gtk3Backend.swift, Sources/GtkBackend/GtkBackend.swift, Sources/SwiftCrossUI/Backend/AppBackend.swift, Sources/SwiftCrossUI/Backend/MenuImplementationStyle.swift, Sources/SwiftCrossUI/Views/Menu.swift, Sources/UIKitBackend/UIKitBackend+Control.swift, Sources/UIKitBackend/UIKitBackend+Menu.swift, Sources/UIKitBackend/UIKitBackend.swift, Sources/WinUIBackend/WinUIBackend.swift
=> Implement Menu in UIKitBackend

.github/workflows/swift-uikit.yml, Sources/UIKitBackend/KeyboardToolbar.swift, Sources/UIKitBackend/UIKitBackend+Control.swift
Only includes the build step and not the test step because `xcodebuild -scheme swift-cross-ui-Package test` errors out looking for GTK headers.
=> Build UIKitBackend in CI

Package.resolved, Package.swift
change "apple" dependencies to "swiftlang" to get rid of these warnings
`warning: 'swift-cross-ui': 'swift-cross-ui' dependency on 'https://github.com/apple/swift-syntax.git' conflicts with dependency on 'https://github.com/swiftlang/swift-syntax.git' which has the same identity 'swift-syntax'. this will be escalated to an error in future versions of SwiftPM.`
=> Get rid of "apple" vs "swiftlang" package resolution warnings

Examples/Sources/WindowingExample/WindowingApp.swift
```swift
macro expansion #hotReloadable:5:25: warning: 'init(_:_:)' is deprecated: Use TextField(_:text:) instead
`- /home/*****/swift-cross-ui/Examples/Sources/WindowingExample/WindowingApp.swift:97:14: note: expanded code originates here
95 |                 }
96 |                 .padding(20)
97 |             }
+--- macro expansion #hotReloadable --------------------------------
| 3 |                     HStack {
| 4 |                         Text("Window title:")
| 5 |                         TextField("My window", $title)
|   |                         |- warning: 'init(_:_:)' is deprecated: Use TextField(_:text:) instead
|   |                         `- note: use 'TextField.init(_:text:)' instead
| 6 |                     }
| 7 | …
```
=> Fix deprecation warning in WindowingApp example

Examples/Sources/GreetingGeneratorExample/GreetingGeneratorApp.swift
```swift
macro expansion #hotReloadable:3:21: warning: 'init(_:_:)' is deprecated: Use TextField(_:text:) instead
`- /home/****/swift-cross-ui/Examples/Sources/GreetingGeneratorExample/GreetingGeneratorApp.swift:47:14: note: expanded code originates here
45 |                 }
46 |                 .padding(10)
47 |             }
+--- macro expansion #hotReloadable ---------------------------------
| 1 | SwiftCrossUI.HotReloadableView {
| 2 |                 VStack {
| 3 |                     TextField("Name", $name)
|   |                     |- warning: 'init(_:_:)' is deprecated: Use TextField(_:text:) instead
|   |                     `- note: use 'TextField.init(_:text:)' instead
| 4 |                     HStack {
| 5 |                         Button("Generate") { …
```
=> Fix deprecation warning in GreetingGeneratorExample

.github/workflows/swift-macos.yml, .github/workflows/swift-uikit.yml, .gitignore, Examples/Bundler.toml, Examples/Package.resolved, Examples/Package.swift, Examples/Sources/PathsExample/PathsApp.swift, Package.resolved, Package.swift, Sources/AppKitBackend/AppKitBackend.swift, Sources/Gtk3Backend/Gtk3Backend.swift, Sources/GtkBackend/GtkBackend.swift, Sources/SwiftCrossUI/Backend/AppBackend.swift, Sources/SwiftCrossUI/Path.swift, Sources/SwiftCrossUI/Views/Shapes/Capsule.swift, Sources/SwiftCrossUI/Views/Shapes/Circle.swift, Sources/SwiftCrossUI/Views/Shapes/Ellipse.swift, Sources/SwiftCrossUI/Views/Shapes/Rectangle.swift, Sources/SwiftCrossUI/Views/Shapes/RoundedRectangle.swift, Sources/SwiftCrossUI/Views/Shapes/Shape.swift, Sources/SwiftCrossUI/Views/Shapes/StyledShape.swift, Sources/UIKitBackend/UIColor+Color.swift, Sources/UIKitBackend/UIKitBackend+Path.swift, Sources/WinUIBackend/WinUIBackend.swift
Not currently implemented in GtkBackend or Gtk3Backend, but I may be able to do the former in the near future
=> Add Path and Shape

Sources/Gtk3Backend/Gtk3Backend.swift, Sources/GtkBackend/GtkBackend.swift
Implements a 'main run loop tickler' that periodically services the main run loop. Enables the use of `@MainActor` and `DispatchQueue.main` under Gtk on non-Apple platforms (gtk already services the main run loop on macOS).
=> GtkBackend,Gtk3Backend: Implement main run loop tickler (fixes #140)

.github/workflows/swift-windows.yml
Took a good minute to build from scratch on my fork, but it's working fine now with the latest commit:
https://github.com/DivineDominion/swift-cross-ui/actions
=> Use modern Swift on latest Windows CI

.github/workflows/swift-linux.yml
=> Add wokrflow to test on ubuntu-22.04, rename swift-linux.yml -> ubuntu-24.04

Examples/Sources/PathsExample/PathsApp.swift, Sources/WinUIBackend/WinUIBackend.swift
After applying a transform, I appended an empty path to the geometry group, so that future lines and Bézier curves would go in that (untransformed) path. However, if you don't have any lines or curves after the transform, that path stays empty, and WinUI really doesn't like rendering empty paths. This PR adds a cleanup pass to remove any empty paths, and adds a custom curve to the PathsExample that previously would have triggered this crash.
=> [WinUIBackend] Prevent crash: remove empty paths

.github/workflows/build-test-and-docs.yml, Package.resolved, Sources/UIKitBackend/UIKitBackend+Picker.swift
Updates Package.resolved so it actually builds, add a CI job for it, and add a missing `#available`.
=> Build for Catalyst

Sources/AppKitBackend/AppKitBackend.swift
This PR makes the following code work as you'd expect (i.e. it will create a TextField with 20pt text);
```swift
TextField("Username", text: $username)
.font(.system(size: 20))
```
GtkBackend already behaves this way.
=> AppKitBackend: Respect environment font when updating text fields

Examples/Sources/CounterExample/CounterApp.swift, Sources/AppKitBackend/AppKitBackend.swift, Sources/Gtk/Utility/CSS/CSSProperty.swift, Sources/Gtk3/Utility/CSS/CSSProperty.swift, Sources/Gtk3Backend/Gtk3Backend.swift, Sources/GtkBackend/GtkBackend.swift, Sources/SwiftCrossUI/Backend/AppBackend.swift, Sources/SwiftCrossUI/Environment/EnvironmentValues.swift, Sources/SwiftCrossUI/Values/DeviceClass.swift, Sources/SwiftCrossUI/Values/Font.swift, Sources/SwiftCrossUI/Values/TextStyle.swift, Sources/SwiftCrossUI/Views/Modifiers/Style/FontModifier.swift, Sources/UIKitBackend/Font+UIFont.swift, Sources/UIKitBackend/UIKitBackend+Control.swift, Sources/UIKitBackend/UIKitBackend+Passive.swift, Sources/UIKitBackend/UIKitBackend.swift, Sources/WinUIBackend/WinUIBackend.swift, Tests/SwiftCrossUITests/SwiftCrossUITests.swift
This PR introduces dynamic text styles with a similar API to SwiftUI. It also expands the existing set of font-related view modifiers, and introduces a set of APIs for constructing new fonts from existing fonts.
The set of text styles supported by SwiftUI differs by platform. I've standardised SwiftCrossUI's text styles on the set of styles supported by SwiftUI on macOS. I've extrapolated values for any text styles that SwiftUI doesn't support on certain platforms.
I've based the font size and weight of each text style off Apple's [typography guidelines](https://developer.apple.com/design/human-interface-guidelines/typography). By default, the text styles are resolved by SwiftCrossUI and only depend on the backend's reported device class (e.g. desktop, tablet, etc). However, backends can …
=> Introduce dynamic text styles and various font modifiers

README.md
This PR adds a new section to the README with step-by-step instructions on how to run the Swift package examples on the iOS Simulator. Since the examples are distributed as Swift packages, they can’t be run directly on iOS without additional setup.
Using tools like [mint](https://github.com/yonaskolb/Mint) and [swift-bundler](https://github.com/stackotter/swift-bundler) simplifies running these examples without needing to create an Xcode project manually. The instructions include installation steps and a sample command to run the CounterExample on the iPhone simulator.
This addition should help new users get started quickly and improve overall developer experience.
=> #194: Add instructions to run examples on iOS Simulator using mint and swift-bundler

README.md, Sources/SwiftCrossUI/SwiftCrossUI.docc/Examples.md
This PR follows on from Vitor Silveira's PR #195 to address issue #194. I've moved the example running instructions to their own subheading, and compressed them down about to keep the README skimmable (with links out to more detailed instructions. I've also updated the list of examples in the documentation while I was at it and copied across the running instruction changes (cause the docs had outdated instructions as well).
=> Update example running instructions in readme and docs (with Vitor Silveira)

Examples/Sources/HoverExample/HoverApp.swift, Sources/SwiftCrossUI/Views/ForEach.swift
https://github.com/stackotter/swift-cross-ui/issues/213
Just adds ForEach Initializers accepting Range<Int> or ClosedRange<Int> and updated HoverExample to use the new initializer instead of the old array hack.
I expect it to work seemlessly across all supported platforms, as its just 2 new initializers
=> [Feat] range foreach
